### ISSUE TITLE
casual read typo

### ISSUE THREAD

**Issue by shinguz** [mariadb-corporation/mysql-wsrep#122]
We are using: mysql-wsrep-5.6.23-25.10 / wsrep-25.3.10 (the very newest).

wsrep-casual-reads is a type in diffent places. Should be wsrep-causal-reads
# my.cnf

wsrep_causal_reads=1

mysql_install_db --datadir=/home/mysql/data/galera3/ --user=mysql --basedir=/home/mysql/product/mysql-wsrep-5.6.23-25.10/
2015-04-15 22:37:05 0 [Warning] WSREP: option --wsrep-casual-reads is deprecated
2015-04-15 22:37:05 0 [Warning] WSREP: --wsrep-casual-reads=ON takes precedence over --wsrep-sync-wait=0. WSREP_SYNC_WAIT_BEFORE_READ is on
...

grep -r casual *
Binary file bin/mysqld matches
mysql-test/include/mtr_warnings.sql: ("WSREP: option --wsrep-casual-reads is deprecated"),
mysql-test/include/mtr_warnings.sql: ("WSREP: --wsrep-casual-reads=ON takes precedence over --wsrep-sync-wait=0"),

**Comment by philip-galera** [comment]
Man you are quick, I assigned this to myself... How does one merge to 5.5 ? An entirely separate commit or some other git operation?

**Comment by ayurchen** [comment]
I think `git cherry-pick` is the way to merge to 5.5. Thanks for reminding about 5.5
