### ISSUE TITLE
Issues with 5.6.23 merge

### ISSUE THREAD

**Issue by ronin13** [mariadb-corporation/mysql-wsrep#123]
Following fixes from upstream (from 5.6.22 tag) are missing:

1acb932392ca39ecb5128bbde83f3e27ea356fec

39ab6439f763e9bf927db7654327934354246418

Please check for others.

**Comment by ronin13** [comment]
305130361bf72726de220f3d2b2787395e10be61 is also missing. 

http://paste.wnohang.net/113eba?diff

**Comment by ayurchen** [comment]
Raghu, where are you getting these commits from?

```
$ git show mysql-5.6.23
commit bcb0bb464582cad2dcef0154111a97a76fdfe93d
Author: s.sujatha <sujatha.sivakumar@oracle.com>
Date:   Mon Jan 19 14:52:05 2015 +0530
```

at the same time

```
commit 305130361bf72726de220f3d2b2787395e10be61
Author: Marc Alff <marc.alff@oracle.com>
Date:   Tue Feb 10 11:31:32 2015 +0100
```

```
commit 39ab6439f763e9bf927db7654327934354246418
Author: Sujatha Sivakumar <sujatha.sivakumar@oracle.com>
Date:   Wed Feb 11 11:10:08 2015 +0530
```

```
commit 1acb932392ca39ecb5128bbde83f3e27ea356fec
Author: Venkatesh Duggirala <venkatesh.duggirala@oracle.com>
Date:   Tue Feb 3 15:00:22 2015 +0530
```

-- they don't seem to be even under mysql-5.6.23 tag.

**Comment by ronin13** [comment]
Yes, it seems strange since,

```
git describe --tags 1acb932392ca39ecb5128bbde83f3e27ea356fec
mysql-5.6.22-147-g1acb932

git describe --tags 39ab6439f763e9bf927db7654327934354246418
mysql-5.6.22-167-g39ab643

git describe --tags 305130361bf72726de220f3d2b2787395e10be61
mysql-5.6.22-165-g3051303
```

However, as you pointed out, 
bcb0bb464582cad2dcef0154111a97a76fdfe93d is indeed where 5.6.23 is tagged.

**Comment by ronin13** [comment]
So, it looks like an issue with tags (git describe should be showing 5.6.23-XYZ-g...for them), so this bug is false positive. Marking as closed.
