### ISSUE TITLE
wsrep_sst_auth password in cleartext in error log and ps

### ISSUE THREAD

**Issue by bstillman** [mariadb-corporation/mysql-wsrep#141]
The SST auth password is in clear text in the error log a ps. Example using xtrabackup-v2 SST method:

150526 15:39:04 [Note] WSREP: Running: 'wsrep_sst_xtrabackup-v2 --role 'joiner' --address 'xxx.xxx.xxx.xxx' --auth 'sst_user:secret' --datadir '/var/lib/mysql/' --defaults-file '/etc/my.cnf' --parent '13238''

mysql     1108  1098  0 16:16 pts/1    00:00:00 /bin/bash -ue /usr//bin/wsrep_sst_xtrabackup-v2 --role joiner --address xxx.xxx.xxx.xxx --auth sst_user:secret --datadir /var/lib/mysql/ --defaults-file /etc/my.cnf --parent 1098

Also on failures:

150526 15:39:04 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_xtrabackup-v2 --role 'joiner' --address 'xxx.xxx.xxx.xxx' --auth 'sst_user:secret' --datadir '/var/lib/mysql/' --defaults-file '/etc/my.cnf' --parent '13238'
        Read: '(null)'
150526 15:39:04 [ERROR] WSREP: Process completed with error: wsrep_sst_xtrabackup-v2 --role 'joiner' --address 'xxx.xxx.xxx.xxx' --auth 'sst_user:secret' --datadir '/var/lib/mysql/' --defaults-file '/etc/my.cnf' --parent '13238': 2 (No such file or directory)

Can this be obfuscated?

**Comment by ayurchen** [comment]
It is relatively straightforward to obfuscate in the error log.
However in the ps output it is not so straightforward to do. Probably it can be done by setting environment variable, e.g. WSREP_SST_AUTH and pass it instead of a value. This automatically would solve error log issue as well.

**Comment by dbadapt** [comment]
Isn't this normally read from the .cnf?

**Comment by bstillman** [comment]
That is coming from wsrep_sst_auth in my.cnf.

**Comment by dbadapt** [comment]
FWIW,  Raghu fixed this in PXC...

  https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1200727

There's a patch for the PXB "v1" SST script here:

  https://bazaar.launchpad.net/~percona-core/percona-xtradb-cluster/5.5/revision/401
