### ISSUE TITLE
my-default.cnf not installed in right directory, affects mysql_install_db

### ISSUE THREAD

**Issue by shinguz** [mariadb-corporation/mysql-wsrep#158]
./scripts/mysql_install_db --datadir=/home/mysql/data/oli --user=mysql
FATAL ERROR: Could not find my-default.cnf

If you compiled from source, you need to run 'make install' to
copy the software into the correct location ready for operation.

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.

echo $?
1

stat("././my-default.cnf", 0x879280)    = -1 ENOENT (No such file or directory)
stat("././my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("././release/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("././debug/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("././relwithdebinfo/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/my-default.cnf", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/release/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/debug/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/relwithdebinfo/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/mysql/my-default.cnf", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/mysql/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/mysql/release/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/mysql/debug/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./share/mysql/relwithdebinfo/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./support-files/my-default.cnf", 0x879280) = -1 ENOENT (No such file or directory)
stat("./support-files/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./support-files/release/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./support-files/debug/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("./support-files/relwithdebinfo/my-default.cnf.exe", 0x879280) = -1 ENOENT (No such file or directory)
stat("", 0x879280)                      = -1 ENOENT (No such file or directory)
stat("./share/my-default.cnf", 0x879280) = -1 ENOENT (No such file or directory)
stat("", 0x879280)                      = -1 ENOENT (No such file or directory)

Workaround: touch my-default.cnf

my-default.cnf should be included in the package at the right location as it is done with Oracle/MySQL packages and not under examples.

**Comment by philip-galera** [comment]
In oracle MySQL, the file is indeed installed under:

```
/usr/share/mysql/my-default.cnf
```

and we install it under

```
/share/doc/mysql-wsrep-server-5.6/examples/my-default.cnf
```
