### ISSUE TITLE
mysql-wsrep-5.6 packages for Ubuntu Vivid do not install

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#171]
I built packages for Ubuntu Vivid but they refuse to install:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-wsrep-5.6 : Depends: mysql-wsrep-client-5.6 (= 5.6.24-25.10.20150818.27bf069-1vivid) but it is not going to be installed
                   Depends: mysql-wsrep-server-5.6 (= 5.6.24-25.10.20150818.27bf069-1vivid) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

https://91.221.67.96:8443/job/test-install-ubuntu/ARCH=amd64,RELEASE=vivid/453/console

**Comment by philip-galera** [comment]
Same issue affects debian sid and debian stretch. The problem is with  libdbd-mysql-perl 

```
galera@stretch:~$ sudo apt-get install mysql-wsrep-client-5.6
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-wsrep-client-5.6 : Depends: libdbd-mysql-perl (>= 1.2202) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

libdbg-mysql-perl exists but is version 4.028-2+b1

**Comment by philip-galera** [comment]
Same problem happens with xenial

**Comment by ottok** [comment]
I tested different scenarios with slightly confusing results, but I think the core problem here is that mysql-5.7 has entered Ubuntu Xenial and introduced a version of libdbd-mysql-perl, which depends in the libmysqlclient20 from mysql-5.7. This creates a conflicting dependency: mysql-wsrep-5.6 needs libdbd-mysql-perl and libmysqlclient18, but the available version of libdbd-mysql-perl depends on libmysqlclient20.

This is a symptom of trying to ship mysql-wsrep-5.6 in a distro that has moved to mysql-5.7. That might not be feasible to do a the distro is designed for mysql-5.7 and reverting all adaptions of that would be too much of work.

The scenario above does however not affect Debian Sid and Ubuntu before Xenial, like Ubuntu Vivid. And Vivid is in general already end-of-life by Ubuntu.

**Comment by ottok** [comment]
@philip-galera Fixed this and made some other minor improvements. Please pull my 5.5 branch with
`git pull git@github.com:ottok/mysql-wsrep.git 5.6 --ff-only` to avoid unnecessary separate merge commit.

MySQL-wsrep dev repos available at http://labs.seravo.fi/~otto/debian/, which I used to repeat the bug and after the fix test that 5.6 now installs on Xenial as intended.

**Comment by philip-galera** [comment]
Pushed.

**Comment by 1391518** [comment]
cat galera.pref
```
# Prefer Codership repository
Package: *
  n: origin releases.galeracluster.com
Pin-Priority: 1001
```
COPY galera.pref /etc/apt/preferences.d/galera.pref
