### ISSUE TITLE
IPv6 support for rsync SST

### ISSUE THREAD

**Issue by bbcorp** [mariadb-corporation/mysql-wsrep#210]
Hi there,
the wsrep with rsync isn't working with IPv6.

Here's my wsrep config : 
wsrep_cluster_address="gcomm://dbcluster1,dbcluster2,dbcluster3,dbcluster4"
wsrep_sst_method=rsync
wsrep_provider_options = "gmcast.listen_addr=tcp://[::]:4567;"
wsrep_node_name="dbcluster1"
wsrep_sst_receive_address="[2a01:e34:ec7d:490::10]:4444"

Here's rsync command launch by wsrep_sst_rsync : 
rsync --daemon --no-detach --port e34 --config /var/lib/mysql//rsync_sst.conf

Port isn't the good one because IPv6 isn't right parsed : 2a01:**e34**:ec7d:490::10

Thanks in advance.

**Comment by ayurchen** [comment]
Do you really need to specify wsrep_sst_receive_address there? Does dbcluster1 resolve to something different?

**Comment by bbcorp** [comment]
In all wsrep config I saw wsrep_sst_receive_address is specified.
And yes dbcluster1 is 2a01:e34:ec7d:490::10 ...

**Comment by ayurchen** [comment]
`wsrep_sst_receive_address` is for the cases when it is different from `wsrep_node_address`. So why not use dbcluster1 instead of IPv6 notation?

**Comment by bbcorp** [comment]
Thanks a lot, it's working now. You're a life saver.
