### ISSUE TITLE
Documentation change request wsrep_debug

### ISSUE THREAD

**Issue by cr-bruderer** [mariadb-corporation/mysql-wsrep#212]
wsrep_debug exposes confidential information (like passwords) to the mysql error log. This is not documented in http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html#wsrep-debug

**Comment by philip-galera** [comment]
Moved to https://github.com/codership/documentation/issues/119https://github.com/codership/documentation/issues/119
