### ISSUE TITLE
If wsrep_on=OFF on a node, there might still be some Galera Cluster communications

### ISSUE THREAD

**Issue by GeoffMontee** [mariadb-corporation/mysql-wsrep#214]
It seems that if you set wsrep_on=OFF, some Galera Cluster communications can still happen.

To demonstrate this, let's start with a 2-node cluster.

```
MariaDB [(none)]> show global status where Variable_name IN('wsrep_cluster_size', 'wsrep_cluster_status', 'wsrep_incoming_addresses');
+--------------------------+-------------------------------------+
| Variable_name            | Value                               |
+--------------------------+-------------------------------------+
| wsrep_incoming_addresses | 172.31.25.43:3306,172.31.25.44:3306 |
| wsrep_cluster_size       | 2                                   |
| wsrep_cluster_status     | Primary                             |
+--------------------------+-------------------------------------+
3 rows in set (0.00 sec)
```

Then let's kill the mysqld process on one node:

```
sudo kill -9 $(sudo pidof mysqld)
```

This will cause the cluster to become a 1-node cluster, and it will be non-Primary, assuming that the nodes use the default values of most wsrep_provider_option settings.

```
MariaDB [(none)]> show global status where Variable_name IN('wsrep_cluster_size', 'wsrep_cluster_status', 'wsrep_incoming_addresses');
+--------------------------+-------------------+
| Variable_name            | Value             |
+--------------------------+-------------------+
| wsrep_incoming_addresses | 172.31.25.44:3306 |
| wsrep_cluster_size       | 1                 |
| wsrep_cluster_status     | non-Primary       |
+--------------------------+-------------------+
3 rows in set (0.00 sec)
```

On the remaining node, let's set:

```
SET GLOBAL wsrep_on=OFF
```

Now, let's bring the killed node back online:

```
sudo service mysql start
```

Even though wsrep_on=OFF, a cluster does seem to get formed:

```
MariaDB [(none)]> show global status where Variable_name IN('wsrep_cluster_size', 'wsrep_cluster_status', 'wsrep_incoming_addresses');
+--------------------------+-------------------------------------+
| Variable_name            | Value                               |
+--------------------------+-------------------------------------+
| wsrep_incoming_addresses | 172.31.25.43:3306,172.31.25.44:3306 |
| wsrep_cluster_size       | 2                                   |
| wsrep_cluster_status     | Primary                             |
+--------------------------+-------------------------------------+
3 rows in set (0.00 sec)
```

Logs are included in the MariaDB JIRA issue as well: https://mariadb.atlassian.net/browse/MDEV-8967

**Comment by philip-galera** [comment]
Hello,

wsrep_on is a session variable and therefore it applies to replicating just the updates made by the session it affects. The node continues to participate in the cluster in other ways.

`SET GLOBAL wsrep_on=OFF` simply causes wsrep_on to be OFF for any future sessions, it does not cause the node to leave the cluster.

**Comment by GeoffMontee** [comment]
Thanks for the clarification, @philip-galera. It might be a good idea to clarify the documentation too:

> This parameter defines whether or not the node participates in replication. When set to OFF, the node functions as a standard standalone MySQL database server. No transactions made during this session replicate to the cluster.

http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html#wsrep-on

Saying that setting `wsrep_on=OFF` allows the server to function as a standalone database server doesn't sound correct to me, given this information. Maybe a description like this would be better:

> This parameter defines whether or not changes from the transactions belonging to a session are replicated. When set to OFF for a particular session, no transactions made during the session replicate to the cluster.
> 
> When set to OFF for all sessions, the node should function similar to a standard standalone MySQL database server, as no transactions will replicate to other nodes. However, although transactions won't replicate, other cluster communications can still happen normally.

**Comment by philip-galera** [comment]
A separate documentation ticket has been opened.
