### ISSUE TITLE
wsrep_provider_options needs to be set twice before the setting becomes visible

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#244]
SET GLOBAL wsrep_provider_options='pc.weight=3' is not immediately reflected when reading wsrep_provider_options back.

SET GLOBAL must be issued twice and only then is the new setting visible.

**Comment by temeo** [comment]
This setting may take some time to take effect as it needs to be communicated between nodes. IIRC there is no check implemented to make sure that this communication actually takes place. Try to add some sleep or poll the setting until it changes.

**Comment by philip-galera** [comment]
Thanks, polling seems to work. Closing the ticket as invalid.
