### ISSUE TITLE
[DOC] innodb_locks_unsafe_For_binlog=1 still required for parallel applying?

### ISSUE THREAD

**Issue by PrzemekMalkowski** [mariadb-corporation/mysql-wsrep#260]
In the documentation:
http://galeracluster.com/documentation-webpages/performance.html?highlight=innodb_locks_unsafe_for_binlog#setting-parallel-slave-threads
we can read:

> Parallel applying requires the following settings:
> 
> innodb_autoinc_lockmode=2
> innodb_locks_unsafe_For_binlog=1

However, I can see Alexey mentioning innodb_locks_unsafe_for_binlog no longer required long time ago:
https://groups.google.com/forum/#!topic/codership-team/dY0KFiu-1r8

Can you correct the documentation if this is the case?

**Comment by philip-galera** [comment]
The documentation has been fixed and will be uploaded to the web site along with our next release.
