### ISSUE TITLE
ALTER USER is not replicated

### ISSUE THREAD

**Issue by henriavelabarbe** [mariadb-corporation/mysql-wsrep#292]
Hi,
from my initial testing, Galera cluster 5.7 doesn't replicate "alter user identified by" ddl command trough the cluster.
'grant usage on _._ to user identified by' is replicated but not the newer syntax.
As 'alter user identified by' seems to be the non-deprecated syntax to update passwords, could you fix that ?

Regards,
Henri Chapelle

**Comment by philip-galera** [comment]
I can confirm it is a more general problem with ALTER USER that affects both 5.6 and 5.7. The following 5.6 statement is also not replicated:

```
ALTER USER 'root'@'localhost'  PASSWORD EXPIRE;
```

**Comment by philip-galera** [comment]
Reported previously as https://bugs.launchpad.net/codership-mysql/+bug/1376269

**Comment by philip-galera** [comment]
This issue has been fixed and the fix will be part of the next release.
