### ISSUE TITLE
segfault when "set wsrep_provider='none'"

### ISSUE THREAD

**Issue by kennt-percona** [mariadb-corporation/mysql-wsrep#308]
This occurs occasionally, to make it more reliable, added 
--- a/galera/src/replicator_smm.cpp
+++ b/galera/src/replicator_smm.cpp
@@ -368,6 +368,12 @@ wsrep_status_t galera::ReplicatorSMM::async_recv(void* recv_ctx)
     {
         ssize_t rc;
 
+        for (int i = 0; i < 20; i++)
+        {
+            fprintf(stderr, "...sleeping %d\n", 20-i);
+            sleep(1);
+        }
+

Then:
(1) Start up a single node
(2) When the "...sleeping" occurs, send "set global wsrep_provider='none';" via the mysql client
(3) Wait for the countdown to finish
(4) Segfault (see stack trace below)

(gdb) bt
#0  0x00007ffff67c3c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff67c7028 in __GI_abort () at abort.c:89
#2  0x00007ffff70d1535 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff70cf6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff70cf703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff70d01bf in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffed803f45 in galera::ReplicatorSMM::async_recv (this=0x1fa28e0, recv_ctx=0x7fff900008c0)
    at galera/src/replicator_smm.cpp:377
#7  0x00007fffed8204fe in galera_recv (gh=0x1f181f0, recv_ctx=0x7fff900008c0)
    at galera/src/wsrep_provider.cpp:244
#8  0x00000000007c55a5 in wsrep_replication_process (thd=0x7fff900008c0)
    at /home/kennt/dev/codership/sql/wsrep_thd.cc:330
#9  0x00000000007a1336 in start_wsrep_THD (arg=arg@entry=0x7c5540 <wsrep_replication_process(THD*)>)
    at /home/kennt/dev/codership/sql/mysqld.cc:6570
#10 0x0000000000f00e61 in pfs_spawn_thread (arg=0x2819930)
    at /home/kennt/dev/codership/storage/perfschema/pfs.cc:2188
#11 0x00007ffff737d184 in start_thread (arg=0x7fffe0204700) at pthread_create.c:312
#12 0x00007ffff688abed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

(gdb) info vtbl as_
vtable for 'galera::ActionSource' @ 0x7fffedb01470 (subobject @ 0x1fa2f98):
[0]: 0x7fffed7e6778 <galera::ActionSource::~ActionSource()>
[1]: 0x7fffed7e67ae <galera::ActionSource::~ActionSource()>
[2]: 0x769d00 <__cxa_pure_virtual@plt>

In another thread, we see ReplicatorSMM in the destructor, while it's still in use.

Thread 37 (Thread 0x7fffe0182700 (LWP 55421)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffed6671dd in fifo_flush (q=0x1fd3210) at galerautils/src/gu_fifo.c:208
#2  0x00007fffed667d7e in gu_fifo_destroy (queue=0x1fd3210) at galerautils/src/gu_fifo.c:478
#3  0x00007fffed7ac80b in gcs_destroy (conn=0x1faa8f0) at gcs/src/gcs.cpp:1471
#4  0x00007fffed80c9ef in galera::Gcs::~Gcs (this=0x1fa2e50, __in_chrg=<optimized out>)
    at galera/src/galera_gcs.hpp:93
#5  0x00007fffed8034b1 in galera::ReplicatorSMM::~ReplicatorSMM (this=0x1fa28e0, 
    __in_chrg=<optimized out>) at galera/src/replicator_smm.cpp:269
#6  0x00007fffed803840 in galera::ReplicatorSMM::~ReplicatorSMM (this=0x1fa28e0, 
    __in_chrg=<optimized out>) at galera/src/replicator_smm.cpp:288
#7  0x00007fffed81f8ee in galera_tear_down (gh=0x1f181f0) at galera/src/wsrep_provider.cpp:103
#8  0x00000000012db79f in wsrep_unload (hptr=0x1f181f0)
    at codership/wsrep/wsrep_loader.c:222
#9  0x00000000007b8d18 in wsrep_deinit () at codership/sql/wsrep_mysqld.cc:665
#10 0x00000000007c1d5d in wsrep_provider_update (self=<optimized out>, thd=0x7fff88000ae0, 
    type=<optimized out>) at codership/sql/wsrep_var.cc:300
#11 0x0000000000c2dbca in sys_var::update (this=0x1d99b00 <Sys_wsrep_provider>, thd=0x7fff88000ae0, 
    var=0x7fff88006240) at codership/sql/set_var.cc:184
#12 0x0000000000c2e227 in set_var::update (this=<optimized out>, thd=<optimized out>)
    at codership/sql/set_var.cc:802
#13 0x0000000000c2eda1 in sql_set_variables (thd=thd@entry=0x7fff88000ae0, 
    var_list=var_list@entry=0x7fff88003240) at codership/sql/set_var.cc:662
#14 0x0000000000cb5408 in mysql_execute_command (thd=thd@entry=0x7fff88000ae0, 
    first_level=first_level@entry=true) at codership/sql/sql_parse.cc:4143
#15 0x0000000000cbacf5 in mysql_parse (thd=thd@entry=0x7fff88000ae0, 
    parser_state=parser_state@entry=0x7fffe0180d80) at codership/sql/sql_parse.cc:6228
#16 0x0000000000cbae13 in wsrep_mysql_parse (thd=thd@entry=0x7fff88000ae0, 
    rawbuf=0x7fff88005710 "set GLOBAL wsrep_provider='none'", length=32, 
    parser_state=parser_state@entry=0x7fffe0180d80) at codership/sql/sql_parse.cc:7149
#17 0x0000000000cbd4fb in dispatch_command (thd=thd@entry=0x7fff88000ae0, 
    com_data=com_data@entry=0x7fffe0181980, command=COM_QUERY)
    at codership/sql/sql_parse.cc:1718
#18 0x0000000000cbe452 in do_command (thd=thd@entry=0x7fff88000ae0)
    at codership/sql/sql_parse.cc:1118
#19 0x0000000000d7c158 in handle_connection (arg=arg@entry=0x285f9c0)
    at codership/sql/conn_handler/connection_handler_per_thread.cc:300
#20 0x0000000000f00e61 in pfs_spawn_thread (arg=0x2819930)
    at codership/storage/perfschema/pfs.cc:2188
#21 0x00007ffff737d184 in start_thread (arg=0x7fffe0182700) at pthread_create.c:312
#22 0x00007ffff688abed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by temeo** [comment]
The fix will be included in upcoming 5.7.27-25.19.
