### ISSUE TITLE
5.7: galera.galera_as_slave_multisource leaks a transaction

### ISSUE THREAD

**Issue by temeo** [mariadb-corporation/mysql-wsrep#329]
After adding new Galera variable wsrep_open_transactions https://github.com/codership/galera/issues/492 the MTR internal check for the test case galera.galera_as_slave_multisource has started failing:
```
--- /home/teemu/work/git/mysql-wsrep-merge/mysql-test/var/tmp/check-mysqld_3.result	2018-05-06 12:07:18.627259212 +0300
+++ /home/teemu/work/git/mysql-wsrep-merge/mysql-test/var/tmp/check-mysqld_3.reject	2018-05-06 12:07:19.831232119 +0300
@@ -992,7 +992,7 @@
 Variable_name	Value
 Slave_open_temp_tables	0
 Variable_name	Value
-wsrep_open_transactions	0
+wsrep_open_transactions	1
 wsrep_open_connections	0
 Table	Checksum
 mysql.columns_priv	0

mysqltest: Result content mismatch
```

This indicates that either there is an open transaction remaining at the end of the test or that a transaction which is executed by the test does not get properly closed in wsrep patch.

**Comment by vasild** [comment]
The `galera.galera_as_slave_multisource` post-test mtr check failure is not due to the merge of mysql-5.7.22 (5b18c9efd00). It has been "failing" before too.
