### ISSUE TITLE
node hang due to conflicting inserts into foreign key child table

### ISSUE THREAD

**Issue by sjaakola** [mariadb-corporation/mysql-wsrep#335]
Cluster node may enter in unresolved conflict state when there are two inserts, with same primary key, into a table which has foreign key constraint for a parent table. These inserts must be issued in separate cluster nodes, and there has to be simultaneous writes (updates or deletes), for the referenced parent row.
As a result of such scenario, replication applier thread may end in unresolved conflict state, end error log will be filled by messages of type:
"WSREP: BF lock wait long" 
followed by InnoDB monitor outputs

**Comment by temeo** [comment]
Fix will be included in mysql-wsrep 5.7.23-25.15.
