### ISSUE TITLE
5.7.23 can cause crash on replay of transaction (if autocommit = off)

### ISSUE THREAD

**Issue by kbauskar** [mariadb-corporation/mysql-wsrep#344]
1. Tried with latest mysql-wsrep 5.7.23 (galera-3.24)

2. Crash  

Debug mode assert:
mysqld: galera/src/replicator_smm.cpp:957: virtual wsrep_status_t galera::ReplicatorSMM::post_rollback(galera::TrxHandle*): Assertion `trx->state() == TrxHandle::S_ABORTING || trx->state() == TrxHandle::S_EXECUTING' failed.

Crashes even in release mode as state transition fails.

3. How to reproduce

Execute galera.galera_transaction_replay ... this will not crash as it default uses AUTOCOMMIT=ON

Now change to use AUTOCOMMIT=OFF and will rely on COMMIT to end the transaction (vs BEGIN as it happens in AUTOCOMMIT=ON)

Check the test-case crashing

4. What regressed ?

When transaction is replayed following flow is executed:

wsrep_replay_transaction -> wsrep_prepare_bf_thd -> THD::init_for_queries -> ha_enable_transaction -> trans_commit_implicit

5. Check in trans_commit_implict turns to true if AUTO_COMMIT=OFF. (check the original mysql comment).

  if (thd->in_multi_stmt_transaction_mode() ||
      (thd->variables.option_bits & OPTION_TABLE_LOCK))
  {

6. Recent added code in wsrep_post_commit to rollback empty trx, tries to rollback replaying transaction
(Note: condition only check for MUST_REPLY by the time this code re-execute through above flow wsrep_conflict_state = REPLAYING)

     /*
       Run post-rollback hook to clean up in the case if
       some keys were populated for the transaction in provider
       but during commit time there was no write set to replicate.
       This may happen when client sets the SAVEPOINT and immediately
       rolls back to savepoint after first operation. 
      */
     if (all && thd->wsrep_conflict_state != MUST_REPLAY &&
         wsrep->post_rollback(wsrep, &thd->wsrep_ws_handle))
     {
         WSREP_WARN("post_rollback fail: %llu %d",
                    (long long)thd->thread_id(), thd->get_stmt_da()->status());
     }

**Comment by kbauskar** [comment]
Workaround: Avoid using AUTOCOMMIT=OFF. (Use auto-commit = on and switch to use begin ... commit statement).

**Comment by temeo** [comment]
@kbauskar Confirmed. Thanks for the detailed bug report!
