### ISSUE TITLE
Make 'service_startup_timeout' configurable from rc.conf

### ISSUE THREAD

**Issue by ltning** [mariadb-corporation/mysql-wsrep#380]
https://github.com/codership/mysql-wsrep/blob/908c06c83db30e34422f147fa29f837fcf1e33cd/support-files/mysql.server.sh#L64

This variable should be configurable in rc.conf(5).

Background:
In some scenarios it is desirable to set this value to 0 to make sure the script does not hold up system startup. This is particularly important when running in a FreeBSD jail(8) along with other jails that are started sequentially. Jail startup is not considered complete until rc(8) finishes, holding up the starting of other jails on the same system. Specifically, if all nodes in a Galera cluster are running in jails on the same system, the cluster may never recover after a restart if the first instance to start up requires SST.

**Comment by sciascid** [comment]
The actual fix should go here:
https://github.com/freebsd/freebsd-ports/blob/master/databases/mysqlwsrep57-server/files/mysql-server.in#L62

I'll keep the issue open here for now, given that freebsd-ports repo doesn't have a issue tracker.

**Comment by sciascid** [comment]
This issue has been fixed here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252264
