### ISSUE TITLE
wsrep_recover does not consider basedir

### ISSUE THREAD

**Issue by shinguz** [mariadb-corporation/mysql-wsrep#409]
We have installed our Galera Cluster binaries NOT at the default location!

When we run wsrep-recover as recommended, we get an error:

shell> ./wsrep_recover
WSREP: Failed to start mysqld for wsrep recovery: './wsrep_recover: 1: eval: /usr/local/mysql/bin/mysqld: not found'

The problem is here:

 25 user="mysql"
 26 **print_defaults="/usr/local/mysql/bin/my_print_defaults"**

 51 wsrep_recover_position() {
 52   # Redirect server's error log to the log file.
 53   **eval /usr/local/mysql/bin/mysqld $cmdline_args --user=$user --wsrep_recover \**
 54     --disable-log-error 2> "$log_file"
 55   ret=$?

So we suggest the following fix:

shell> diff ./wsrep_recover.cp ./wsrep_recover
25d24
< basedir='/usr/local/mysql'
27c26
< print_defaults="${basedir}/bin/my_print_defaults"
---
> print_defaults="/usr/local/mysql/bin/my_print_defaults"
54c53
<   eval ${basedir}/bin/mysqld $cmdline_args --user=$user --wsrep_recover \
---
>   eval /usr/local/mysql/bin/mysqld $cmdline_args --user=$user --wsrep_recover \
84,97d82
< 
< while [ $# -gt 0 ]; do
< case "$1" in
<     '--basedir')
<         basedir=${2}
<         shift
<         ;;
<     *) # must be command
<        # usage
<        # exit 1
<        ;;
< esac
< shift
< done

With this fix it works at least for us:

shell> ./wsrep_recover --basedir /home/mysql/product/mysql-wsrep-8.0
WSREP: Recovered position 8b9e57c1-569c-11ed-8af2-f34c46db9217:30
--wsrep_start_position=8b9e57c1-569c-11ed-8af2-f34c46db9217:30

**Comment by temeo** [comment]
This should now be fixed in 5.7.40-25.32 and 8.0.31-26.12.
