### ISSUE TITLE
wsrep_sst_xtrabackup-v2 is looking at wrong location

### ISSUE THREAD

**Issue by shinguz** [mariadb-corporation/mysql-wsrep#413]
After changing wsrep_sst_method to xtrabackup-v2 and provoking an SST we get the following error in the MySQL error log:

Unable to find xtrabackup plugin dir at either /usr/lib/plugin or /usr/lib/xtrabackup/plugin

Checking on the filesystem we find the following:

ll -d /usr/lib/xtrabackup /usr/lib/plugin /usr/lib64/xtrabackup
ls: cannot access '/usr/lib/plugin': No such file or directory
drwxr-xr-x 3 root root 4096 May 15 15:22 /usr/lib64/xtrabackup
lrwxrwxrwx 1 root root   21 May 16 11:00 /usr/lib/xtrabackup -> /usr/lib64/xtrabackup   # This link is created by us!

After creating the link it worked...

Bug is located here:

wsrep_sst_xtrabackup-v2

   1591     pxb_root="${XTRABACKUP_80_PATH%/*}"
   1592     pxb_bin_path="${pxb_root}/bin/xtrabackup"
   1593     pxb_plugin_dir="${pxb_root}/lib/xtrabackup/plugin"
   1594     [ -d "${pxb_plugin_dir}" ] || pxb_plugin_dir="${pxb_root}/lib/plugin"
   1595     if [[ -d "${pxb_plugin_dir}" ]]; then
   1596         wsrep_log_debug "using '${pxb_plugin_dir}' for xtrabackup plugin dir"
   1597     else
   1598         wsrep_log_error "******************* FATAL ERROR ********************** "
   1599         wsrep_log_error "Unable to find xtrabackup plugin dir at either ${pxb_plugin_dir} or ${pxb_root}/lib/xtrabackup/plugin"
   1600         wsrep_log_error "Line $LINENO"
   1601         wsrep_log_error "****************************************************** "
   1602         exit 2
   1603     fi

**Comment by shinguz** [comment]
O/S is RockyLinux 8. On DEB distros it should work...

**Comment by temeo** [comment]
Was xtrabackup installed from RPM or from binary tarball?

**Comment by shinguz** [comment]
RPM

**Comment by temeo** [comment]
Fixed in 8.0.33-26.14
