### ISSUE TITLE
/etc/rc.d/init.d/mysql is set to print every command executed by default

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#47]
/etc/rc.d/init.d/mysql is run under a bash -x shebang, which causes it to be verbose. This is in contrast to init scripts provided by other vendors or products.

I tested on centos 6 and 7

**Comment by temeo** [comment]
The init script does not seem to set -x, it may be the test script itself which does it.

**Comment by philip-galera** [comment]
No, I see -x at the top of /etc/rc.d/init.d/mysql

**Comment by philip-galera** [comment]
```
[root@centos6 galera]# head -1 /etc/rc.d/init.d/mysql
#!/bin/sh -x
```

**Comment by temeo** [comment]
It probably comes from test script:

```
    sudo sed -i 's/^#!\/bin\/sh/#!\/bin\/sh -x/' /etc/init.d/mysql
```

The script https://github.com/codership/mysql-wsrep/blob/5.6/support-files/mysql.server.sh does not have it.

**Comment by philip-galera** [comment]
oh , ok, so not a bug then.
