### ISSUE TITLE
FLUSH PRIVILEGES is binlogged but not replicated via wsrep

### ISSUE THREAD

**Issue by ayurchen** [mariadb-corporation/mysql-wsrep#67]
This introduces master position inconsistency between the nodes (for slave failover)
Details here: https://bugs.launchpad.net/bugs/1421360

**Comment by philip-galera** [comment]
Reported previously here https://bugs.launchpad.net/codership-mysql/+bug/1376692

**Comment by philip-galera** [comment]
Request for FLUSH QUERY CACHE:

https://bugs.launchpad.net/codership-mysql/+bug/1359801
