### ISSUE TITLE
Remove Debian debug and metapackages

### ISSUE THREAD

**Issue by philip-galera** [mariadb-corporation/mysql-wsrep#72]
because they are missing a version and will conflict with 5.5

Also remove them from 5.5

**Comment by philip-galera** [comment]
Pushed in 5.6 waiting for 5.5 debian files to push the fix there as well.

**Comment by philip-galera** [comment]
Unfortunately simply commenting out the packages as in commit 95b25c7  did not work.

Errors were encountered during installation, so I will need to ask Otto to look into this.

The command that is used was:

```
sudo -E apt-get install -y mysql-wsrep-5.6
```

and the error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-wsrep-5.6 : Depends: mysql-wsrep-client-5.6 (= 5.6.23-25.9.20150225.95b25c7-1wheezy) but it is not going to be installed
                   Depends: mysql-wsrep-server-5.6 (= 5.6.23-25.9.20150225.95b25c7-1wheezy) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ottok** [comment]
By debug packages you mean mysql-wsrep-server-5.5-dbg and mysql-wsrep-client-5.5-dbg. These where added especially for MySQL wsrep 5.6 - why do you now want to remove them from both 5.5 and 5.6?

By removing metapackages, which packages in particular do you mean? Can you elaborate what "missing version" and "conflict" means in this context?

**Comment by philip-galera** [comment]
We are not stripping the binaries, so separate debug packages are not required for either version.

With respect to metapackages, we are concerned that both 5.5 and 5.6 will contain packages named e.g. "mysql-server", without a version number in its name. There will be conflicts, especially given that we are putting both packages in the same repository. Metapackages that have the version number in the name should remain.

Same for "mysql-client", etc.

**Comment by ottok** [comment]
These kind of packages are originally not designed to reside in the same repository, so this might require some major changes. Maybe we should leave mysql-wsrep-5.6 as it is and then strip all conflicting contents from mysql-wsrep-5.5 so that it can reside in the same repository as 5.6.

**Comment by philip-galera** [comment]
I guess that would work too.

**Comment by ottok** [comment]
I'm calling the client libs in 5.5 now mysql-wsrep-libmysqlclient18.0 (and in 5.6 we should call it .1 as the libs are actually not the same version). The common package that has the configs will be called mysql-wsrep-5.5. Versionless metapackages are removed.

**Comment by ottok** [comment]
The size of mysql-wsrep-server-5.5_5.5.41-1_amd64.deb is now 14 MB - I suspect that it does not actually have debug symbols inside. At least MariaDB with debug symbols is in the range of 50-70 MB. How do I check if a binary has debug symbols or not? (other than by crashing it and looking at the stack trace)

**Comment by temeo** [comment]
> How do I check if a binary has debug symbols or not?

At least `file` command shows if the binary is stripped:

```
$ file /usr/bin/mysql
/usr/bin/mysql: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=a772df17c821eea2f648b3d881bebfa99c553c50, stripped
```

**Comment by philip-galera** [comment]
mysql-wsrep-server-5.6_5.6.23-25.9.20150226.d8fda73-1wheezy_amd64.deb is 60M, so there must be some difference between 5.5 and 5.6

**Comment by philip-galera** [comment]
mysql-wsrep-server-5.5_5.5.42-25.11.20150224.541a412-1wheezy_amd64.deb  is 14M

**Comment by ottok** [comment]
The stanza 'override_dh_strip' in debian/rules file is supposed to skip the stripping (or move the debug symbols to another location/package) but it does not seem to have the desired effect at the moment:

```
$ file usr/bin/mysql*
usr/bin/mysqlbinlog:                ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x303a738381139a653f3f228592ea166a6eaa31ea, stripped
usr/bin/mysqltest:                  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x483450cb576059d0766789af485881a1a20ed793, stripped
usr/bin/mysql_tzinfo_to_sql:        ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xa1612c15f739d1ef3c4150a4d6495c668841f274, stripped
usr/bin/mysql_upgrade:              ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xb318127f0072ca429bb922af132d2952f24bbafb, stripped
```

I need to continue investigating this. The changes so far have been pushed to my branch.

**Comment by ottok** [comment]
Ok, found the cure in https://github.com/ottok/mysql-wsrep/commit/ea42ef4ed1aa1dc6461da6245779bc08ced9c804

```
usr/sbin/mysqld: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x6f87b28acbc1dbd024297d0213dbda9ef3d5db10, not stripped

-rwxr-xr-x 1 otto otto 13M helmi 26 11:16 usr/sbin/mysqld
```

**Comment by ottok** [comment]
These issues were fixed on Feb 26th in commit before and uptil https://github.com/ottok/mysql-wsrep/commit/ea42ef4ed1aa1dc6461da6245779bc08ced9c804

**Comment by philip-galera** [comment]
Fixed.
